/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.main.view;

import org.main.contoller.FrameSetProperties;

/**
 *
 * @author ashish
 */
public class MainPage extends javax.swing.JFrame {

    /**
     * Creates new form MainPage
     */
    public MainPage() {
        initComponents();
//        new FrameSetProperties().SetDate(dateAndTimeLabel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        leftSidePanel = new javax.swing.JPanel();
        inquiryDeletedButton = new javax.swing.JButton();
        newGroupButton = new javax.swing.JButton();
        inquiryCallingButton = new javax.swing.JButton();
        inquiryLoginButton = new javax.swing.JButton();
        newInquiryButton = new javax.swing.JButton();
        rightSidePanel = new javax.swing.JPanel();
        grouploginButton = new javax.swing.JButton();
        groupCallingButton = new javax.swing.JButton();
        groupBugsButton = new javax.swing.JButton();
        groupQueriesButton = new javax.swing.JButton();
        groupDeletedButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Main ");
        setBackground(java.awt.Color.white);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 237, 204));

        jPanel2.setBackground(new java.awt.Color(255, 237, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "MAIN PAGE", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Verdana", 0, 12), new java.awt.Color(255, 153, 0))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(0, 153, 0));

        leftSidePanel.setBackground(new java.awt.Color(255, 237, 204));

        inquiryDeletedButton.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        inquiryDeletedButton.setForeground(new java.awt.Color(255, 153, 0));
        inquiryDeletedButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/main/icon/delete.png"))); // NOI18N
        inquiryDeletedButton.setText(" INQUIRY DELETED");
        inquiryDeletedButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        inquiryDeletedButton.setContentAreaFilled(false);
        inquiryDeletedButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        newGroupButton.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        newGroupButton.setForeground(new java.awt.Color(255, 153, 0));
        newGroupButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/main/icon/User-Group-icon.png"))); // NOI18N
        newGroupButton.setText("NEW GROUP");
        newGroupButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        newGroupButton.setContentAreaFilled(false);
        newGroupButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        newGroupButton.setIconTextGap(17);
        newGroupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newGroupButtonActionPerformed(evt);
            }
        });

        inquiryCallingButton.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        inquiryCallingButton.setForeground(new java.awt.Color(255, 153, 0));
        inquiryCallingButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/main/icon/callcenter-girls-blonde-icon (1).png"))); // NOI18N
        inquiryCallingButton.setText("INQUIRY CALLING");
        inquiryCallingButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        inquiryCallingButton.setContentAreaFilled(false);
        inquiryCallingButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        inquiryCallingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inquiryCallingButtonActionPerformed(evt);
            }
        });

        inquiryLoginButton.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        inquiryLoginButton.setForeground(new java.awt.Color(255, 153, 0));
        inquiryLoginButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/main/icon/logout-icon.png"))); // NOI18N
        inquiryLoginButton.setText("INQUIRY LOGIN");
        inquiryLoginButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        inquiryLoginButton.setContentAreaFilled(false);
        inquiryLoginButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        inquiryLoginButton.setIconTextGap(9);

        newInquiryButton.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        newInquiryButton.setForeground(new java.awt.Color(255, 153, 0));
        newInquiryButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/main/icon/callcenter-girls-blonde-icon (1).png"))); // NOI18N
        newInquiryButton.setText("NEW INQUIRY");
        newInquiryButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        newInquiryButton.setContentAreaFilled(false);
        newInquiryButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        newInquiryButton.setIconTextGap(10);
        newInquiryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newInquiryButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout leftSidePanelLayout = new javax.swing.GroupLayout(leftSidePanel);
        leftSidePanel.setLayout(leftSidePanelLayout);
        leftSidePanelLayout.setHorizontalGroup(
            leftSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(inquiryLoginButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(newGroupButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(inquiryCallingButton, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
            .addComponent(inquiryDeletedButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(newInquiryButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        leftSidePanelLayout.setVerticalGroup(
            leftSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftSidePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(newInquiryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inquiryLoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(newGroupButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inquiryCallingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inquiryDeletedButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        rightSidePanel.setBackground(new java.awt.Color(255, 237, 204));

        grouploginButton.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        grouploginButton.setForeground(new java.awt.Color(255, 153, 0));
        grouploginButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/main/icon/logout-icon.png"))); // NOI18N
        grouploginButton.setText("GROUP LOGIN");
        grouploginButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        grouploginButton.setContentAreaFilled(false);
        grouploginButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        grouploginButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        grouploginButton.setIconTextGap(8);

        groupCallingButton.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        groupCallingButton.setForeground(new java.awt.Color(255, 153, 0));
        groupCallingButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/main/icon/callcenter-girls-blonde-icon (1).png"))); // NOI18N
        groupCallingButton.setText("GROUP CALLING");
        groupCallingButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        groupCallingButton.setContentAreaFilled(false);
        groupCallingButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        groupCallingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                groupCallingButtonActionPerformed(evt);
            }
        });

        groupBugsButton.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        groupBugsButton.setForeground(new java.awt.Color(255, 153, 0));
        groupBugsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/main/icon/User-Group-icon.png"))); // NOI18N
        groupBugsButton.setText("GROUP BUGS");
        groupBugsButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        groupBugsButton.setContentAreaFilled(false);
        groupBugsButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        groupBugsButton.setIconTextGap(12);
        groupBugsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                groupBugsButtonActionPerformed(evt);
            }
        });

        groupQueriesButton.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        groupQueriesButton.setForeground(new java.awt.Color(255, 153, 0));
        groupQueriesButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/main/icon/User-Group-icon.png"))); // NOI18N
        groupQueriesButton.setText("GROUP QUERIES");
        groupQueriesButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        groupQueriesButton.setContentAreaFilled(false);
        groupQueriesButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        groupQueriesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                groupQueriesButtonActionPerformed(evt);
            }
        });

        groupDeletedButton.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        groupDeletedButton.setForeground(new java.awt.Color(255, 153, 0));
        groupDeletedButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/main/icon/delete.png"))); // NOI18N
        groupDeletedButton.setText("GROUP DELETED");
        groupDeletedButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        groupDeletedButton.setContentAreaFilled(false);
        groupDeletedButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        groupDeletedButton.setPreferredSize(new java.awt.Dimension(184, 377));

        javax.swing.GroupLayout rightSidePanelLayout = new javax.swing.GroupLayout(rightSidePanel);
        rightSidePanel.setLayout(rightSidePanelLayout);
        rightSidePanelLayout.setHorizontalGroup(
            rightSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(groupDeletedButton, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
            .addGroup(rightSidePanelLayout.createSequentialGroup()
                .addGroup(rightSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(groupQueriesButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                    .addComponent(groupCallingButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                    .addComponent(groupBugsButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                    .addComponent(grouploginButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        rightSidePanelLayout.setVerticalGroup(
            rightSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rightSidePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(grouploginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(groupQueriesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(groupCallingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(groupBugsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(groupDeletedButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(leftSidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 399, Short.MAX_VALUE)
                .addComponent(rightSidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(leftSidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rightSidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(25, 25, 25))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newInquiryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newInquiryButtonActionPerformed
        // TODO add your handling code here:
        new QuickInquiryDetail().setVisible(true);
    }//GEN-LAST:event_newInquiryButtonActionPerformed

    private void newGroupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newGroupButtonActionPerformed
        // TODO add your handling code here:
        new ProjectGroupDetailPage().setVisible(true);
    }//GEN-LAST:event_newGroupButtonActionPerformed

    private void inquiryCallingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inquiryCallingButtonActionPerformed
        // TODO add your handling code here:
       new InquiryTelecallingpage().setVisible(true);
    }//GEN-LAST:event_inquiryCallingButtonActionPerformed

    private void groupBugsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_groupBugsButtonActionPerformed
        // TODO add your handling code here:
        new GroupBugsPage().setVisible(true);
    }//GEN-LAST:event_groupBugsButtonActionPerformed

    private void groupCallingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_groupCallingButtonActionPerformed
        // TODO add your handling code here:
        new GroupTellingCallingPage().setVisible(true);
    }//GEN-LAST:event_groupCallingButtonActionPerformed

    private void groupQueriesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_groupQueriesButtonActionPerformed
        // TODO add your handling code here:
        new Groupquerydetail().setVisible(true);
    }//GEN-LAST:event_groupQueriesButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton groupBugsButton;
    private javax.swing.JButton groupCallingButton;
    private javax.swing.JButton groupDeletedButton;
    private javax.swing.JButton groupQueriesButton;
    private javax.swing.JButton grouploginButton;
    private javax.swing.JButton inquiryCallingButton;
    private javax.swing.JButton inquiryDeletedButton;
    private javax.swing.JButton inquiryLoginButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel leftSidePanel;
    private javax.swing.JButton newGroupButton;
    private javax.swing.JButton newInquiryButton;
    private javax.swing.JPanel rightSidePanel;
    // End of variables declaration//GEN-END:variables

   
}
