/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.main.view;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.text.JTextComponent;
import org.hibernate.metamodel.domain.Superclass;
import org.main.contoller.FrameSetProperties;
import org.main.model.ProjectComboModel;
import org.main.pojo.TblProject;
import org.main.util.SuperConnection;

/**
 *
 * @author ashish
 */
public class ProjectDetailPage extends javax.swing.JFrame {

    /**
     * Creates new form ProjectDetailPage
     */
    public ProjectDetailPage() {
        initComponents();
        loadCombo();
        loadProjectCategriesCombo();
        loadTechnologyNameCombo();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        openFileChooser = new javax.swing.JFileChooser();
        jPanel2 = new javax.swing.JPanel();
        subPanel = new javax.swing.JPanel();
        projectCategoryComboBox = new javax.swing.JComboBox();
        projectNameLabel = new javax.swing.JLabel();
        projectNameTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        abstractTextArea = new javax.swing.JTextArea();
        projectPPtButton = new javax.swing.JButton();
        projectPPtTextField = new javax.swing.JTextField();
        projectVideoButton = new javax.swing.JButton();
        projectVideoTextField = new javax.swing.JTextField();
        projectThesisLabel = new javax.swing.JLabel();
        abstracrLabel = new javax.swing.JLabel();
        synopsisLabel = new javax.swing.JLabel();
        thesisButton = new javax.swing.JButton();
        projectThesisTextField = new javax.swing.JTextField();
        projectVideoLabel = new javax.swing.JLabel();
        flowDiagramLabel = new javax.swing.JLabel();
        synopsisButton = new javax.swing.JButton();
        flowDiagramButton = new javax.swing.JButton();
        synopsisTextField = new javax.swing.JTextField();
        flowDiagramTextField = new javax.swing.JTextField();
        ieeePaperLabel = new javax.swing.JLabel();
        ieeePaperButton = new javax.swing.JButton();
        ieeePaperTextField = new javax.swing.JTextField();
        projectPPtLabel = new javax.swing.JLabel();
        technologyNameLabel = new javax.swing.JLabel();
        technologyNameComboBox = new javax.swing.JComboBox();
        projectCategoryLabel = new javax.swing.JLabel();
        viewProjectButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Project Entry Form");
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(255, 237, 204));

        subPanel.setBackground(new java.awt.Color(255, 237, 204));
        subPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PROJECT DETAILS", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Verdana", 0, 12), new java.awt.Color(255, 153, 0))); // NOI18N
        subPanel.setForeground(new java.awt.Color(0, 153, 0));

        projectCategoryComboBox.setBackground(new java.awt.Color(255, 204, 51));
        projectCategoryComboBox.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        projectCategoryComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        projectCategoryComboBox.setMaximumSize(null);

        projectNameLabel.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        projectNameLabel.setText("  Project Name :");

        projectNameTextField.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        abstractTextArea.setColumns(20);
        abstractTextArea.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        abstractTextArea.setRows(5);
        jScrollPane1.setViewportView(abstractTextArea);

        projectPPtButton.setBackground(new java.awt.Color(255, 204, 51));
        projectPPtButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projectPPtButtonActionPerformed(evt);
            }
        });

        projectPPtTextField.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        projectPPtTextField.setText(" ");

        projectVideoButton.setBackground(new java.awt.Color(255, 204, 51));
        projectVideoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projectVideoButtonActionPerformed(evt);
            }
        });

        projectVideoTextField.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        projectVideoTextField.setText(" ");
        projectVideoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projectVideoTextFieldActionPerformed(evt);
            }
        });

        projectThesisLabel.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        projectThesisLabel.setText("Project Thesis :\n");

        abstracrLabel.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        abstracrLabel.setText("  Abstract :");

        synopsisLabel.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        synopsisLabel.setText(" Synopsis :  ");

        thesisButton.setBackground(new java.awt.Color(255, 204, 51));
        thesisButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thesisButtonActionPerformed(evt);
            }
        });

        projectThesisTextField.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        projectThesisTextField.setText(" ");

        projectVideoLabel.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        projectVideoLabel.setText(" Project Video : ");

        flowDiagramLabel.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        flowDiagramLabel.setText(" Flow Diagram :");

        synopsisButton.setBackground(new java.awt.Color(255, 204, 51));
        synopsisButton.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        synopsisButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                synopsisButtonActionPerformed(evt);
            }
        });

        flowDiagramButton.setBackground(new java.awt.Color(255, 204, 51));
        flowDiagramButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flowDiagramButtonActionPerformed(evt);
            }
        });

        synopsisTextField.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        synopsisTextField.setText(" ");

        flowDiagramTextField.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        flowDiagramTextField.setText(" ");

        ieeePaperLabel.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        ieeePaperLabel.setText("IEEE Papers :");

        ieeePaperButton.setBackground(new java.awt.Color(255, 204, 51));
        ieeePaperButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ieeePaperButtonActionPerformed(evt);
            }
        });

        ieeePaperTextField.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        ieeePaperTextField.setText(" ");
        ieeePaperTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ieeePaperTextFieldActionPerformed(evt);
            }
        });

        projectPPtLabel.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        projectPPtLabel.setText("Project PPT  :");

        technologyNameLabel.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        technologyNameLabel.setText("  Technology Name :");

        technologyNameComboBox.setBackground(new java.awt.Color(255, 204, 51));
        technologyNameComboBox.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        technologyNameComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        technologyNameComboBox.setMaximumSize(null);

        projectCategoryLabel.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        projectCategoryLabel.setText("Project Category :");

        viewProjectButton.setBackground(new java.awt.Color(255, 204, 51));
        viewProjectButton.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        viewProjectButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/main/icon/reports-icon (1).png"))); // NOI18N
        viewProjectButton.setText("  VIEW PROJECT");
        viewProjectButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 153, 0), 1, true));
        viewProjectButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        viewProjectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewProjectButtonActionPerformed(evt);
            }
        });

        saveButton.setBackground(new java.awt.Color(255, 204, 51));
        saveButton.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        saveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/main/icon/Device-Floppy-icon.png"))); // NOI18N
        saveButton.setText("SAVE");
        saveButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 153, 0), 1, true));
        saveButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        saveButton.setIconTextGap(5);
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        resetButton.setBackground(new java.awt.Color(255, 204, 51));
        resetButton.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        resetButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/main/icon/refresh-icon.png"))); // NOI18N
        resetButton.setText("RESET");
        resetButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 153, 0), 1, true));
        resetButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel4.setText("PROJECT ENTRY FORM");

        javax.swing.GroupLayout subPanelLayout = new javax.swing.GroupLayout(subPanel);
        subPanel.setLayout(subPanelLayout);
        subPanelLayout.setHorizontalGroup(
            subPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, subPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(subPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(subPanelLayout.createSequentialGroup()
                        .addGroup(subPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(technologyNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(projectNameLabel))
                        .addGap(25, 25, 25)
                        .addGroup(subPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(subPanelLayout.createSequentialGroup()
                                .addComponent(technologyNameComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(projectCategoryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(projectCategoryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(115, 115, 115))
                            .addComponent(projectNameTextField)
                            .addComponent(jScrollPane1)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, subPanelLayout.createSequentialGroup()
                        .addGroup(subPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(subPanelLayout.createSequentialGroup()
                                .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(viewProjectButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(resetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, subPanelLayout.createSequentialGroup()
                                .addGroup(subPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(projectVideoLabel)
                                    .addComponent(synopsisLabel))
                                .addGap(67, 67, 67)
                                .addGroup(subPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(subPanelLayout.createSequentialGroup()
                                        .addComponent(synopsisButton, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(synopsisTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(subPanelLayout.createSequentialGroup()
                                        .addComponent(projectVideoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(projectVideoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(subPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(projectThesisLabel)
                                    .addComponent(ieeePaperLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(subPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(thesisButton, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ieeePaperButton, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(subPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ieeePaperTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(projectThesisTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(subPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(subPanelLayout.createSequentialGroup()
                                .addComponent(flowDiagramLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(flowDiagramButton, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(flowDiagramTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(subPanelLayout.createSequentialGroup()
                                .addComponent(projectPPtLabel)
                                .addGap(18, 18, 18)
                                .addComponent(projectPPtButton, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(projectPPtTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, subPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(313, 313, 313))
            .addGroup(subPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(subPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(abstracrLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(713, Short.MAX_VALUE)))
        );
        subPanelLayout.setVerticalGroup(
            subPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subPanelLayout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(subPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(projectCategoryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(projectCategoryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(technologyNameComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(technologyNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(subPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(projectNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(projectNameLabel))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(subPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(subPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(synopsisButton, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(subPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(synopsisTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ieeePaperLabel))
                        .addComponent(ieeePaperButton, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(subPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ieeePaperTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(projectPPtLabel))
                        .addComponent(projectPPtTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(synopsisLabel)
                    .addComponent(projectPPtButton, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 21, Short.MAX_VALUE)
                .addGroup(subPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(projectVideoButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(projectVideoTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(projectThesisLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, subPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(thesisButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(projectThesisTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(flowDiagramButton, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(flowDiagramTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(flowDiagramLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(projectVideoLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(subPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(viewProjectButton, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(resetButton, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(saveButton, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(subPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(subPanelLayout.createSequentialGroup()
                    .addGap(224, 224, 224)
                    .addComponent(abstracrLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(249, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(subPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(subPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void projectPPtButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projectPPtButtonActionPerformed
        // TODO add your handling code here:
        openFileChooser = new JFileChooser();
        String path = new FrameSetProperties().getFileChooserPAth(openFileChooser);
        projectPPtTextField.setText(path);
    }//GEN-LAST:event_projectPPtButtonActionPerformed

    private void projectVideoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projectVideoButtonActionPerformed
        // TODO add your handling code here:
        openFileChooser = new JFileChooser();
        String path = new FrameSetProperties().getFileChooserPAth(openFileChooser);
        projectVideoTextField.setText(path);
    }//GEN-LAST:event_projectVideoButtonActionPerformed

    private void projectVideoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projectVideoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_projectVideoTextFieldActionPerformed

    private void thesisButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thesisButtonActionPerformed
        // TODO add your handling code here:
        openFileChooser = new JFileChooser();
        String path = new FrameSetProperties().getFileChooserPAth(openFileChooser);
        projectThesisTextField.setText(path);
    }//GEN-LAST:event_thesisButtonActionPerformed

    private void synopsisButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_synopsisButtonActionPerformed
        // TODO add your handling code here:
        openFileChooser = new JFileChooser();
        String path = new FrameSetProperties().getFileChooserPAth(openFileChooser);
        synopsisTextField.setText(path);
    }//GEN-LAST:event_synopsisButtonActionPerformed

    private void flowDiagramButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flowDiagramButtonActionPerformed
        // TODO add your handling code here:
        openFileChooser = new JFileChooser();
        String path = new FrameSetProperties().getFileChooserPAth(openFileChooser);
        flowDiagramTextField.setText(path);
    }//GEN-LAST:event_flowDiagramButtonActionPerformed

    private void ieeePaperButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ieeePaperButtonActionPerformed
        // TODO add your handling code here:
        openFileChooser = new JFileChooser();
        String path = new FrameSetProperties().getFileChooserPAth(openFileChooser);
        ieeePaperTextField.setText(path);
    }//GEN-LAST:event_ieeePaperButtonActionPerformed

    private void ieeePaperTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ieeePaperTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ieeePaperTextFieldActionPerformed

    private void viewProjectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewProjectButtonActionPerformed
        // TODO add your handling code here:
        new ViewProjectPage().setVisible(true);
    }//GEN-LAST:event_viewProjectButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        try {
            //        try {
                // TODO add your handling code here:
                TblProject tblProject = new TblProject();
//                tblProject.setTxtId("1");
//                tblProject.setTxtTechnologyName(technologyNameComboBox.getName());
//                tblProject.setTxtProjectCategory(projectCategoryComboBox.getSelectedItem().toString());
//                tblProject.setTxtProjectName(projectNameTextField.getText());
//                tblProject.setTxtAbstract(abstractTextArea.getText());
//                tblProject.setTxtSynopsis(synopsisTextField.getText());// folder or file to be set
//                tblProject.setTxtThesis(projectThesisTextField.getText());// folder or file to be set
//                tblProject.setTxtIeee(ieeePaperTextField.getText()); // folder or file to be set
//                tblProject.setTxtVideo(projectVideoTextField.getText());// folder or file to be set
//                tblProject.setTxtPpt(projectPPtTextField.getText());// folder or file to be set
//                tblProject.setTxtFlowDiagram(flowDiagramTextField.getText());// folder or file to be set
//                tblProject.setTxtEntryDate(new Date());
                SuperConnection.saveEntity(tblProject);
                //        } catch (Exception ex) {
                //            Logger.getLogger(ProjectDetailPage.class.getName()).log(Level.SEVERE, null, ex);
                //        }
        } catch (Exception ex) {
            Logger.getLogger(ProjectDetailPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        // TODO add your handling code here:
        //logic for reset
       new FrameSetProperties().ResetAll(subPanel);
    }//GEN-LAST:event_resetButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProjectDetailPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProjectDetailPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProjectDetailPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProjectDetailPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProjectDetailPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel abstracrLabel;
    private javax.swing.JTextArea abstractTextArea;
    private javax.swing.JButton flowDiagramButton;
    private javax.swing.JLabel flowDiagramLabel;
    private javax.swing.JTextField flowDiagramTextField;
    private javax.swing.JButton ieeePaperButton;
    private javax.swing.JLabel ieeePaperLabel;
    private javax.swing.JTextField ieeePaperTextField;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JFileChooser openFileChooser;
    private javax.swing.JComboBox projectCategoryComboBox;
    private javax.swing.JLabel projectCategoryLabel;
    private javax.swing.JLabel projectNameLabel;
    private javax.swing.JTextField projectNameTextField;
    private javax.swing.JButton projectPPtButton;
    private javax.swing.JLabel projectPPtLabel;
    private javax.swing.JTextField projectPPtTextField;
    private javax.swing.JLabel projectThesisLabel;
    private javax.swing.JTextField projectThesisTextField;
    private javax.swing.JButton projectVideoButton;
    private javax.swing.JLabel projectVideoLabel;
    private javax.swing.JTextField projectVideoTextField;
    private javax.swing.JButton resetButton;
    private javax.swing.JButton saveButton;
    private javax.swing.JPanel subPanel;
    private javax.swing.JButton synopsisButton;
    private javax.swing.JLabel synopsisLabel;
    private javax.swing.JTextField synopsisTextField;
    private javax.swing.JComboBox technologyNameComboBox;
    private javax.swing.JLabel technologyNameLabel;
    private javax.swing.JButton thesisButton;
    private javax.swing.JButton viewProjectButton;
    // End of variables declaration//GEN-END:variables

    private void loadCombo() {
        try {
            List<TblProject> listEntity = SuperConnection.listEntity(new TblProject());
            projectCategoryComboBox.setModel(new ProjectComboModel((ArrayList<TblProject>) listEntity));
        } catch (Exception ex) {
            Logger.getLogger(ProjectDetailPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void loadTechnologyNameCombo() {
    }

    private void loadProjectCategriesCombo() {
    }
}
