package org.main.pojo;
// Generated Nov 20, 2016 3:22:35 PM by Hibernate Tools 4.3.1



/**
 * TblEmployee generated by hbm2java
 */
public class TblEmployee  implements java.io.Serializable {


     private String txtId;
     private String txtEmpName;
     private String txtEmpEmail;
     private String txtPhoneNo;
     private String txtMobileNo;
     private String txtPassword;
     private String txtEmployeeRole;
     private Character txtIsActive;

    public TblEmployee() {
    }

	
    public TblEmployee(String txtId) {
        this.txtId = txtId;
    }
    public TblEmployee(String txtId, String txtEmpName, String txtEmpEmail, String txtPhoneNo, String txtMobileNo, String txtPassword, String txtEmployeeRole, Character txtIsActive) {
       this.txtId = txtId;
       this.txtEmpName = txtEmpName;
       this.txtEmpEmail = txtEmpEmail;
       this.txtPhoneNo = txtPhoneNo;
       this.txtMobileNo = txtMobileNo;
       this.txtPassword = txtPassword;
       this.txtEmployeeRole = txtEmployeeRole;
       this.txtIsActive = txtIsActive;
    }
   
    public String getTxtId() {
        return this.txtId;
    }
    
    public void setTxtId(String txtId) {
        this.txtId = txtId;
    }
    public String getTxtEmpName() {
        return this.txtEmpName;
    }
    
    public void setTxtEmpName(String txtEmpName) {
        this.txtEmpName = txtEmpName;
    }
    public String getTxtEmpEmail() {
        return this.txtEmpEmail;
    }
    
    public void setTxtEmpEmail(String txtEmpEmail) {
        this.txtEmpEmail = txtEmpEmail;
    }
    public String getTxtPhoneNo() {
        return this.txtPhoneNo;
    }
    
    public void setTxtPhoneNo(String txtPhoneNo) {
        this.txtPhoneNo = txtPhoneNo;
    }
    public String getTxtMobileNo() {
        return this.txtMobileNo;
    }
    
    public void setTxtMobileNo(String txtMobileNo) {
        this.txtMobileNo = txtMobileNo;
    }
    public String getTxtPassword() {
        return this.txtPassword;
    }
    
    public void setTxtPassword(String txtPassword) {
        this.txtPassword = txtPassword;
    }
    public String getTxtEmployeeRole() {
        return this.txtEmployeeRole;
    }
    
    public void setTxtEmployeeRole(String txtEmployeeRole) {
        this.txtEmployeeRole = txtEmployeeRole;
    }
    public Character getTxtIsActive() {
        return this.txtIsActive;
    }
    
    public void setTxtIsActive(Character txtIsActive) {
        this.txtIsActive = txtIsActive;
    }




}


