package org.main.pojo;
// Generated Nov 20, 2016 3:22:35 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * TblInquiryTelecalling generated by hbm2java
 */
public class TblInquiryTelecalling  implements java.io.Serializable {


     private String txtId;
     private String txtInquiryId;
     private String txtCallingSubjet;
     private Date txtCallingTime;
     private String txtCallerName;
     private String txtConversation;

    public TblInquiryTelecalling() {
    }

	
    public TblInquiryTelecalling(String txtId, Date txtCallingTime) {
        this.txtId = txtId;
        this.txtCallingTime = txtCallingTime;
    }
    public TblInquiryTelecalling(String txtId, String txtInquiryId, String txtCallingSubjet, Date txtCallingTime, String txtCallerName, String txtConversation) {
       this.txtId = txtId;
       this.txtInquiryId = txtInquiryId;
       this.txtCallingSubjet = txtCallingSubjet;
       this.txtCallingTime = txtCallingTime;
       this.txtCallerName = txtCallerName;
       this.txtConversation = txtConversation;
    }
   
    public String getTxtId() {
        return this.txtId;
    }
    
    public void setTxtId(String txtId) {
        this.txtId = txtId;
    }
    public String getTxtInquiryId() {
        return this.txtInquiryId;
    }
    
    public void setTxtInquiryId(String txtInquiryId) {
        this.txtInquiryId = txtInquiryId;
    }
    public String getTxtCallingSubjet() {
        return this.txtCallingSubjet;
    }
    
    public void setTxtCallingSubjet(String txtCallingSubjet) {
        this.txtCallingSubjet = txtCallingSubjet;
    }
    public Date getTxtCallingTime() {
        return this.txtCallingTime;
    }
    
    public void setTxtCallingTime(Date txtCallingTime) {
        this.txtCallingTime = txtCallingTime;
    }
    public String getTxtCallerName() {
        return this.txtCallerName;
    }
    
    public void setTxtCallerName(String txtCallerName) {
        this.txtCallerName = txtCallerName;
    }
    public String getTxtConversation() {
        return this.txtConversation;
    }
    
    public void setTxtConversation(String txtConversation) {
        this.txtConversation = txtConversation;
    }




}


