package org.main.pojo;
// Generated Nov 20, 2016 3:22:35 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * TblLogincounter generated by hbm2java
 */
public class TblLogincounter  implements java.io.Serializable {


     private String txtId;
     private String txtEmailId;
     private String txtFromIp;
     private Date txtLoginDate;
     private String txtUserType;

    public TblLogincounter() {
    }

	
    public TblLogincounter(String txtId, String txtUserType) {
        this.txtId = txtId;
        this.txtUserType = txtUserType;
    }
    public TblLogincounter(String txtId, String txtEmailId, String txtFromIp, Date txtLoginDate, String txtUserType) {
       this.txtId = txtId;
       this.txtEmailId = txtEmailId;
       this.txtFromIp = txtFromIp;
       this.txtLoginDate = txtLoginDate;
       this.txtUserType = txtUserType;
    }
   
    public String getTxtId() {
        return this.txtId;
    }
    
    public void setTxtId(String txtId) {
        this.txtId = txtId;
    }
    public String getTxtEmailId() {
        return this.txtEmailId;
    }
    
    public void setTxtEmailId(String txtEmailId) {
        this.txtEmailId = txtEmailId;
    }
    public String getTxtFromIp() {
        return this.txtFromIp;
    }
    
    public void setTxtFromIp(String txtFromIp) {
        this.txtFromIp = txtFromIp;
    }
    public Date getTxtLoginDate() {
        return this.txtLoginDate;
    }
    
    public void setTxtLoginDate(Date txtLoginDate) {
        this.txtLoginDate = txtLoginDate;
    }
    public String getTxtUserType() {
        return this.txtUserType;
    }
    
    public void setTxtUserType(String txtUserType) {
        this.txtUserType = txtUserType;
    }




}


