package org.main.pojo;
// Generated Nov 20, 2016 3:22:35 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * TblOutsourceProject generated by hbm2java
 */
public class TblOutsourceProject  implements java.io.Serializable {


     private String txtId;
     private String txtOutsourceId;
     private String txtGroupId;
     private String txtProjectId;
     private String txtAmount;
     private String txtDeliveryDate;
     private String txtRemark;
     private String txtCol3mark;
     private String txtCol4mark;
     private String txtCol5mark;
     private String txtFromIp;
     private Date txtEntryDate;
     private String txtEnteredBy;
     private Date txtUpdateDate;
     private String txtUpdateBy;
     private Character txtIsDelete;
     private Character txtIsActive;

    public TblOutsourceProject() {
    }

	
    public TblOutsourceProject(String txtId, String txtGroupId) {
        this.txtId = txtId;
        this.txtGroupId = txtGroupId;
    }
    public TblOutsourceProject(String txtId, String txtOutsourceId, String txtGroupId, String txtProjectId, String txtAmount, String txtDeliveryDate, String txtRemark, String txtCol3mark, String txtCol4mark, String txtCol5mark, String txtFromIp, Date txtEntryDate, String txtEnteredBy, Date txtUpdateDate, String txtUpdateBy, Character txtIsDelete, Character txtIsActive) {
       this.txtId = txtId;
       this.txtOutsourceId = txtOutsourceId;
       this.txtGroupId = txtGroupId;
       this.txtProjectId = txtProjectId;
       this.txtAmount = txtAmount;
       this.txtDeliveryDate = txtDeliveryDate;
       this.txtRemark = txtRemark;
       this.txtCol3mark = txtCol3mark;
       this.txtCol4mark = txtCol4mark;
       this.txtCol5mark = txtCol5mark;
       this.txtFromIp = txtFromIp;
       this.txtEntryDate = txtEntryDate;
       this.txtEnteredBy = txtEnteredBy;
       this.txtUpdateDate = txtUpdateDate;
       this.txtUpdateBy = txtUpdateBy;
       this.txtIsDelete = txtIsDelete;
       this.txtIsActive = txtIsActive;
    }
   
    public String getTxtId() {
        return this.txtId;
    }
    
    public void setTxtId(String txtId) {
        this.txtId = txtId;
    }
    public String getTxtOutsourceId() {
        return this.txtOutsourceId;
    }
    
    public void setTxtOutsourceId(String txtOutsourceId) {
        this.txtOutsourceId = txtOutsourceId;
    }
    public String getTxtGroupId() {
        return this.txtGroupId;
    }
    
    public void setTxtGroupId(String txtGroupId) {
        this.txtGroupId = txtGroupId;
    }
    public String getTxtProjectId() {
        return this.txtProjectId;
    }
    
    public void setTxtProjectId(String txtProjectId) {
        this.txtProjectId = txtProjectId;
    }
    public String getTxtAmount() {
        return this.txtAmount;
    }
    
    public void setTxtAmount(String txtAmount) {
        this.txtAmount = txtAmount;
    }
    public String getTxtDeliveryDate() {
        return this.txtDeliveryDate;
    }
    
    public void setTxtDeliveryDate(String txtDeliveryDate) {
        this.txtDeliveryDate = txtDeliveryDate;
    }
    public String getTxtRemark() {
        return this.txtRemark;
    }
    
    public void setTxtRemark(String txtRemark) {
        this.txtRemark = txtRemark;
    }
    public String getTxtCol3mark() {
        return this.txtCol3mark;
    }
    
    public void setTxtCol3mark(String txtCol3mark) {
        this.txtCol3mark = txtCol3mark;
    }
    public String getTxtCol4mark() {
        return this.txtCol4mark;
    }
    
    public void setTxtCol4mark(String txtCol4mark) {
        this.txtCol4mark = txtCol4mark;
    }
    public String getTxtCol5mark() {
        return this.txtCol5mark;
    }
    
    public void setTxtCol5mark(String txtCol5mark) {
        this.txtCol5mark = txtCol5mark;
    }
    public String getTxtFromIp() {
        return this.txtFromIp;
    }
    
    public void setTxtFromIp(String txtFromIp) {
        this.txtFromIp = txtFromIp;
    }
    public Date getTxtEntryDate() {
        return this.txtEntryDate;
    }
    
    public void setTxtEntryDate(Date txtEntryDate) {
        this.txtEntryDate = txtEntryDate;
    }
    public String getTxtEnteredBy() {
        return this.txtEnteredBy;
    }
    
    public void setTxtEnteredBy(String txtEnteredBy) {
        this.txtEnteredBy = txtEnteredBy;
    }
    public Date getTxtUpdateDate() {
        return this.txtUpdateDate;
    }
    
    public void setTxtUpdateDate(Date txtUpdateDate) {
        this.txtUpdateDate = txtUpdateDate;
    }
    public String getTxtUpdateBy() {
        return this.txtUpdateBy;
    }
    
    public void setTxtUpdateBy(String txtUpdateBy) {
        this.txtUpdateBy = txtUpdateBy;
    }
    public Character getTxtIsDelete() {
        return this.txtIsDelete;
    }
    
    public void setTxtIsDelete(Character txtIsDelete) {
        this.txtIsDelete = txtIsDelete;
    }
    public Character getTxtIsActive() {
        return this.txtIsActive;
    }
    
    public void setTxtIsActive(Character txtIsActive) {
        this.txtIsActive = txtIsActive;
    }




}


